# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: What does a hacker look like? | The Daily Californian
email: projects@dailycal.org
description: UC Berkeley's EECS department has the lowest proportion of female graduates of any department on campus. It's put programs in place to close the gap â€” but how far can they go?
  
baseurl: "/cs-gender" # the subpath of your site, e.g. /blog
url: "http://projects.dailycal.org/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
